### ISSUE TITLE
支持GPU加速吗？

### ISSUE THREAD

**Issue by yujun-8848** [pengxiao-song/LaWGPT#11]
通过启动git下的代码，log提示：已安装的bitsandbytes版本是在没有GPU支持的情况下编译的
是否该项目目前不支持使用GPU加速；
我在huggingface上面体验了在线的lawgpt，响应速度比较慢。

**Comment by baiyutang** [comment]
我启动会报错，你那有吗？
![image](https://github.com/pengxiao-song/LaWGPT/assets/10782183/29cadc78-521b-4fb8-bbf2-b3a5ca26c215)

**Comment by pengxiao-song** [comment]
您好，本地部署后是支持GPU加速的，请根据报错信息在本地查找下问题～
