### ISSUE TITLE
运行generate.sh报错

### ISSUE THREAD

**Issue by jasonma2014** [pengxiao-song/LaWGPT#16]
git clone 以后，安装venv, 然后pip安装好了依赖后，执行以下的命令报错：

(venv) ➜  LaWGPT git:(main) sh src/scripts/generate.sh
/Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/majian/Projects/LaWGPT/generate.py': [Errno 2] No such file or directory

这个generate.py 是在哪里呢。

**Comment by baiyutang** [comment]
命令 https://github.com/pengxiao-song/LaWGPT/blob/main/src/scripts/generate.sh 
这里的内容要改下。 你说的文件在 src 下
```
#!/bin/bash
CUDA_VISIBLE_DEVICES=1 python src/generate.py \
    --load_8bit \
    --base_model 'minlik/chinese-llama-7b-merged' \
    --lora_weights 'entity303/lawgpt-lora-7b' \
    --prompt_template 'law_template' \
    --share_gradio

```

**Comment by pengxiao-song** [comment]
> 命令 https://github.com/pengxiao-song/LaWGPT/blob/main/src/scripts/generate.sh 这里的内容要改下。 你说的文件在 src 下
> 
> ```
> #!/bin/bash
> CUDA_VISIBLE_DEVICES=1 python src/generate.py \
>     --load_8bit \
>     --base_model 'minlik/chinese-llama-7b-merged' \
>     --lora_weights 'entity303/lawgpt-lora-7b' \
>     --prompt_template 'law_template' \
>     --share_gradio
> ```

不好意思，文件路径有偏差，请参考上述回答，根据本地文件路径修改。
