### ISSUE TITLE
关于训练过程的两个步骤

### ISSUE THREAD

**Issue by pangwenfeng** [pengxiao-song/LaWGPT#2]
你好，感谢你们的工作~
      按照你们的主页，你们的训练过程包含两个步骤，其中使用的脚本是相同的，而使用的数据集不同，我是否可以理解两个数据集主要是在在数据形式上不同？即第一个数据集是生成的形式，而第二个数据集是问答的形式。是否可以给出两个数据集的例子样本呢？谢谢~

**Comment by pengxiao-song** [comment]
谢谢！已更新最新版的示例数据和脚本文件，请您查看。

下面回答您的问题：
1. 训练和精调脚本基本一致，仅在于由于数据格式区别导致 `generate_and_tokenize_prompt` 函数略有不同。
2. 您对数据集的理解是正确的。第一个数据集不是问答形式（法律文书），第二个数据集是问答形式（法律问答数据）。

**Comment by pangwenfeng** [comment]
你好，请问怎样访问新版的示例数据呢，我看了下你们页面还是没找到链接或者data文件夹。

**Comment by pengxiao-song** [comment]
您好，示例数据格式如下：

https://github.com/pengxiao-song/LaWGPT/tree/main/src/data

**Comment by EasyLuck** [comment]
> https://github.com/pengxiao-song/LaWGPT/tree/main/src/data

你这个数据没开放啊？打开是个空的 404
404 - page not found
The 
main
 branch of 
LaWGPT
 does not contain the path 
src/data.

**Comment by lyq080700** [comment]
能否提供一下数据集样例呢
