### ISSUE TITLE
'gbk' codec can't decode byte 0xaf in position 95: illegal multibyte sequence

### ISSUE THREAD

**Issue by Rex0731** [pengxiao-song/LaWGPT#30]
请问一下大佬，Windows10 ，Python3.8 运行报错，具体信息如下：
![image](https://github.com/pengxiao-song/LaWGPT/assets/25200961/bdef635a-4b75-4dad-98f5-7ce450dc52ca)
![image](https://github.com/pengxiao-song/LaWGPT/assets/25200961/10752434-6dd4-40a6-928a-f3e927383c2c)

**Comment by pengxiao-song** [comment]
您好，请您尽可能在 Linux 环境下部署，windows 环境可能会存在各种问题。
