### ISSUE TITLE
想法不谋而合，请问可以私聊吗？

### ISSUE THREAD

**Issue by Ying-ZHANG20** [pengxiao-song/LaWGPT#36]
我觉得你们做的项目非常棒，敬佩。我们最近也在思考一个项目，跟你们理念几乎完全一样，但我们的LawGPT是基于法语的（不是中文）。请问不知道你们有没有时间可以私聊？感谢。我的微信是snawandeva。

**Comment by pengxiao-song** [comment]
您好，感谢关注！可以邮件联系。

**Comment by Ying-ZHANG20** [comment]
你好，

我是张颖，人在London。我 （科技产品管理背景）跟我的一个Backend工程师朋友现在有一个创业的想法，是做法语版针对法务工作人的ChatGPT。有几个问题想请教一下大家：

我想请问你们做的项目大概是几个工程师花了多长时间做出来的？这样可以帮助我们更好的规划我们的时间资源。

请问你们的项目是业余爱好，还是政府/学校为你们的项目提供支持？（我理解你们不是商业用途。）

请问是否方便交流一下你们开发中的困难？如果不敏感的话。

非常感谢，如果你们能回复的话，如果不能回复，也完全没有关系。

祝好，

张颖


On 23 May 2023, at 16:59, Pengxiao Song ***@***.***> wrote:



您好，感谢关注！可以邮件联系。
