### ISSUE TITLE
抱歉打扰。法律从业但编程小白，是否有docker自托管可能性

### ISSUE THREAD

**Issue by sebastian0619** [pengxiao-song/LaWGPT#37]
开发者您好！

请问一下本项目是否有可能通过docker实现在NAS上的自托管，继而有可能实现类似GPT在任何设备上外网访问本项目的可能性？

编程方面纯小白，只是因为有NAS所以经常用docker托管一些方便自己和工作的项目，但也仅此而已了。如果问题比较蠢请见谅

**Comment by lostliam** [comment]
理论可以，进行docker部署加内网穿透。

**Comment by sebastian0619** [comment]
未来是否有这方面的计划？我觉得一部分类似我这种的使用者最多就会配置一下基于现成镜像的docker-compose文件，涉及编写dockerfile，自己构建镜像会比较困难(
> 理论可以，进行docker部署加内网穿透。

**Comment by WNJXYK** [comment]
封装成 Docker 镜像技术上没有难度，但项目**流畅**运行依赖于**性能较强**的 GPU。经典 Nas 品牌 (例如：群晖、威联通) 的硬件配置可能无法承担此项目。

**Comment by sebastian0619** [comment]
感谢解答！
> 封装成 Docker 镜像技术上没有难度，但项目流畅运行依赖于性能较强的 GPU。经典 Nas 品牌 (例如：群晖、威联通) 的硬件配置可能无法承担此项目。

**Comment by csh0101** [comment]
> 封装成 Docker 镜像技术上没有难度，但项目**流畅**运行依赖于**性能较强**的 GPU。经典 Nas 品牌 (例如：群晖、威联通) 的硬件配置可能无法承担此项目。

很好奇，封装镜像的时候，要不要把推理模型的权重也封装进去，还是启动的时候下载（

**Comment by WNJXYK** [comment]
> > 封装成 Docker 镜像技术上没有难度，但项目**流畅**运行依赖于**性能较强**的 GPU。经典 Nas 品牌 (例如：群晖、威联通) 的硬件配置可能无法承担此项目。
> 
> 很好奇，封装镜像的时候，要不要把推理模型的权重也封装进去，还是启动的时候下载（

两种选择都是能操作的。一般来说，不封装进 Docker 镜像，在第一次使用的时候下载更合适。
