### ISSUE TITLE
部署系统问题

### ISSUE THREAD

**Issue by kostya-sec** [pengxiao-song/LaWGPT#38]
请问当前的包只能部署在Linux环境下吗？Windows环境会找不到cuda环境 
总会出这方面的报错RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes
但是我本地包括我的依赖环境确实已经装了cuda。

**Comment by pengxiao-song** [comment]
非项目问题，请自行解决，强烈建议在 Linux 环境下部署
