### ISSUE TITLE
生成内容重复，并且非正常停止

### ISSUE THREAD

**Issue by cxj01** [pengxiao-song/LaWGPT#41]
![image](https://github.com/pengxiao-song/LaWGPT/assets/37614132/fcff9d87-fcba-4588-a3a1-ba031b0bdea1)

**Comment by pengxiao-song** [comment]
您好，感谢反馈！由于参数、基座模型等因素影响，输出内容还无法做到十分稳健。我们后续会进一步增强数据、优化模型，争取取得更稳健的表现。
