### ISSUE TITLE
每次不同的问题，都需要手动调节下参数，然后看看哪个答案好吗？

### ISSUE THREAD

**Issue by thewintersun** [pengxiao-song/LaWGPT#47]
例子中不同的问题，我看截图中的参数都不一样，好像参数不同，有的结果会不断重复。 
![image](https://github.com/pengxiao-song/LaWGPT/assets/8595690/980ca6dc-3cc5-4e5d-af9b-d276396b29f4)

**Comment by pengxiao-song** [comment]
结果中的重复和基座模型相关，基于 LLaMA 的模型基本都会有这个问题，后期我们会继续改进。

另外，手动调整不同的参数容易调出坏的结果，不推荐调整默认参数。截图中参数不一样，是因为项目进展较快，还没有建立完备的评测机制，细节问题没有照顾完全，敬请谅解！
