### ISSUE TITLE
安装依赖后显示缺少fire

### ISSUE THREAD

**Issue by xhh-arr** [pengxiao-song/LaWGPT#52]
运行pip install -r requirements.txt后未报错，再运行webiu.sh时提示Traceback (most recent call last):
  File "/Users/xhh/Desktop/LAW/LaWGPT/webui.py", line 4, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'；
执行pip install fire后显示Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: fire in /opt/homebrew/lib/python3.11/site-packages (0.5.0)
Requirement already satisfied: six in /opt/homebrew/lib/python3.11/site-packages (from fire) (1.16.0)
Requirement already satisfied: termcolor in /opt/homebrew/lib/python3.11/site-packages (from fire) (2.3.0)，fire已安装；
运行conda list后显示# Name                    Version                   Build  Channel
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2023.01.10           hca03da5_0  
libffi                    3.4.4                hca03da5_0  
ncurses                   6.4                  h313beb8_0  
openssl                   1.1.1t               h1a28f6b_0  
pip                       23.0.1          py310hca03da5_0  
python                    3.10.11              hc0d8a6c_2  
readline                  8.2                  h1a28f6b_0  
setuptools                66.0.0          py310hca03da5_0  
sqlite                    3.41.2               h80987f9_0  
tk                        8.6.12               hb8d0fd4_0  
tzdata                    2023c                h04d1e81_0  
wheel                     0.38.4          py310hca03da5_0  
xz                        5.4.2                h80987f9_0  
zlib                      1.2.13               h5a0b063_0  ，表明conda无法识别fire，请问如何解决？

**Comment by gck0514** [comment]
1,pip install fire  done  安装成功，但运行webiu.sh时提示报错 缺少gradio
2,pip install gradio  done  炒鸡慢
