### ISSUE TITLE
关于预训练第一阶段

### ISSUE THREAD

**Issue by nuoma** [pengxiao-song/LaWGPT#6]
非常棒的工作！ymcui的repository里指出第一阶段：冻结transformer参数，仅训练embedding，在尽量不干扰原模型的情况下适配新增的中文词向量。这样看来这一步应该是加入新的法律词表以后需要做的事情，有在工作计划里吗？

**Comment by nuoma** [comment]
如果不去做法律词表扩充，只用ymcui给出的广义中文词表，会有什么影响呢？我只能想出会导致同一句话，分词前后的长度不同，但似乎并不会影响最终的结果吧？ 感谢解答！

**Comment by pengxiao-song** [comment]
谢谢！这两个问题我最初也思考过。

1. 关于问题“是否加入工作计划”，我认为优先级不需要很高。ymcui 说明了“先冻结参数训练新增的词向量，然后再做二次训练”是在摸索阶段采取的一种技术路线，但我认为加入新增词表直接二次训练也是一种可取的方式，不过二者的分词效果和最终性能差距如何，需要做实验来比较。

2. 我不是 NLP 专家，这里谈一下我的想法，不对请指正。我认为增加法律词表是一个小的改进，增加法律词表或许会在少许 case 下会有更好的表现（比如流畅度、知识准确度），但只用广义中文词表也是可以的。加入法律词表对最终结果会产生一定影响，因为 tokenize 后的词元序列变了，基于此训练出的 word embedding 也会有所不同，最终的生成概率也相应有所改变。
