### ISSUE TITLE
关于反例和卡时的估计

### ISSUE THREAD

**Issue by nuoma** [pengxiao-song/LaWGPT#7]
您好！麻烦是否可以给出训练使用了多少卡时的估计吗？
另，法律方向应该由专业人士来做评判，现在有没有效果不好的negative example呢？这并没有在repository里找到。
谢谢!

**Comment by pengxiao-song** [comment]
训练细节请 @herobrine19 介绍下。

当前版本还处于雏形阶段，negative example 是一定存在的，目前还没有系统性的测试评估。您可以根据个人需要进行测试，非常欢迎您的反馈和建议，谢谢！

**Comment by herobrine19** [comment]
> 

您好, 使用8*V100训练时长大约12个小时.

**Comment by pengxiao-song** [comment]
您好，卡时已更新到 README，请参考.
